---

# UnInstall rabbitmq

- name: pre validation steps for UnInstall
  include: uninstall.yml

# Install rabbitmq

- name: Pre validation steps for Install
  include: install.yml

#  - name: start service rabbitmq
#  enable: rabbitmq

# set crontab

- name: "Create directory"
  file:
     path: /opt/crontab/
     state: directory
     owner: eco
     group: eco
      mode: 0755

- name: Check the crontab script
  local_action: stat path="../crontab/rabbitmq.sh"
  register: secfile
  ignore_errors: True
   tags:
     - crontab_rabbitmq

- name: "Copy the script"
  copy:
    src: "../crontab/rabbitmq.sh"
    dest: /opt/crontab/rabbitmq.sh
  when:
    - secfile.stat.exists
  tag:
    - crontab_rabbitmq

- name: "Cron job"
  cron:
    name: "check rabbitmq running"
    minute: "*/24"
    job: "bash /opt/crontab/rabbitmq.sh"

