---
# remove the old version of rabbitmq

- name: Checks whether the rabbitmq is disabled
  command: /etc/init.d/rabbitmq stop
  register: stop-config
  ignore_errors: True
  become: yes

# Remove rabbitmq from start on boot

- name: Remove rabbitmq from chkconfig
  command: chkconfig --del rabbitmq
  register: del-config
  ignore_errors: True
  become: yes

- name: Removing rabbitmq home
  file:
  path: "{{ item }}"
  state: absent
  with_items:
    - /opt/pace/
    - /collect/data/
    - /etc/init.d/
    - /etc/sysconfig/
    - /etc/logrotate.d/
  ignore_errors: True
  become: yes

# name: pre-uninstallation of rabbitmq
# script: pre_uninstall.sh
#become: yes
# when: force is defined and force|bool == true
   # ignore_errors: yes
    # tags:
      #  - pre_uninstall
 
# post-unistallation
 
   #- name: post-uninstallation of rabbitmq
   # script: post_uninstall.sh
   #become: yes
   # when: force is defined and force|bool == true
   # ignore_errors: yes
   # tags:
   #   - post_uninstall#
