---
    
# UnInstall elastic search 

- name: pre validation steps for UnInstall
  include: uninstall.yml

# Install elastic search

- name: Pre validation steps for Install
  include: install.yml

#- name: start service elastic search
 # enable: elasticsearch

# set crontab  

- name: "Create directory"
  file:
    path: /opt/crontab/
    state: directory
    owner: eco
    group: eco
    mode: 0755

- name: Check the crontab script
  local_action: stat path="../crontab/elasticsearch.sh"
  register: secfile
  ignore_errors: True
  tags:
    - crontab_elasticsearch


- name: "Copy the script"
  copy:
    src: "../crontab/elasticsearch.sh"
    dest: /opt/crontab/elasticsearch.sh
  when:
    - secfile.stat.exists
  tag:
    - crontab_elasticsearch     

- name: "Cron job"
  cron:
    name: "check elasticsearch running"
    minute: "*/24"
    job: "bash /opt/crontab/elasticsearch.sh"



